language: python
python:
    - "3.6"
env:
  - DJANGO_VERSION=2.1
  - DJANGO_SETTINGS_MODULE=authors.settings

install:
    - pip install -r requirements.txt

script:
    - python manage.py test

after_success:
  - coveralls
